version: '3.8'
services:
# Web 文件管理
  dufs:
    image: sigoden/dufs
    container_name: dufs
    restart: unless-stopped
    volumes:
      - /root/VintageUser:/data
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    command: /data -A
    networks:
      - vintagevigil
# 爬虫    
  VintageVigil:
    image: samiya777/vintagevigil:latest
    container_name: vintagevigil
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"    
    volumes:
      - /root/VintageUser/.env:/root/VintageVigil/.env # 环境变量
      - /root/VintageUser/lx:/root/VintageVigil/user/lx # 配置文件
    networks:
      - vintagevigil

networks:
    vintagevigil:
      driver: bridge