user = "Admin"

[notify]
telegram_chat_id = "5710592740"
wecom_user_id = "LongXiang"
tg_send_type = 3

[websites.lashinbang]
enabled = true
delay = 600
[[websites.lashinbang.searches]]
keyword = "家庭教師ヒットマンREBORN"
notify = 2

[websites.mercari]
enabled = true
delay = 0.5
[[websites.mercari.searches]]
keyword = "家庭教師ヒットマンREBORN"
notify = 1

[websites.mercari_user]
enabled = true
delay = 1
[[websites.mercari_user.searches]]
keyword = "269741600"
notify = 2
[[websites.mercari_user.searches]]
keyword = "956719196"
notify = 2
[[websites.mercari_user.searches]]
keyword = "891752336"
notify = 2
[[websites.mercari_user.searches]]
keyword = "190540464"
notify = 2
[[websites.mercari_user.searches]]
keyword = "862829897"
notify = 2


[websites.jumpshop]
enabled = true
delay = 1200
[[websites.jumpshop.searches]]
keyword = "呪術廻戦"
notify = 2
[[websites.jumpshop.searches]]
keyword = "家庭教師ヒットマンREBORN"
notify = 2


[websites.suruga]
enabled = true
delay = 180
[[websites.suruga.searches]]
keyword = "https://www.suruga-ya.jp/search?category=10&search_word=%E5%AE%B6%E5%BA%AD%E6%95%99%E5%B8%AB%E3%83%92%E3%83%83%E3%83%88%E3%83%9E%E3%83%B3REBORN+-%E3%82%AD%E3%83%A3%E3%83%A9%E3%82%AF%E3%82%BF%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88+-%E7%94%9F%E5%86%99%E7%9C%9F&adult_s=1&inStock=Off&is_marketplace=0&rankBy=modificationTime%3Adescending"
notify = 2