# 任你购 配置
# 官网: https://rennigou.jp

# 任你购 网站的搜索设置
[[websites.rennigou.searches]]
# 搜索关键字，必填项
keyword = "家庭教師ヒットマンREBORN"

# 搜索网站，必填项
# all, mercari, yahooauction, rakuma, amazon, surugaya
websiteType = "mercari"

# 通知方式
# from * to *
# 必填项
# 第一项 @Samiya310Bot（1），@Lihahadear_bot（2），企业微信Samiya（3）
# 第二项 根据notify中填的ids定
notify = [1,2]


[websites.rennigou.searches.filter]
# 通用过滤器
# 排序
# mercari 空/推荐排序 price_asc/价格从低到高 price_desc/价格从高到低 new/上架日期从近到远 like_desc/点赞从多到少
# surugaya 空/默认 price_asc/价格从低到高 price_desc/价格从高到低 new_publish/新上架商品 publish_time_asc/发售日从近到远 publish_time_desc/发售日从远到近
sortOrder = "new"

# 价格
priceMin = ""
priceMax = ""

# 煤炉
# 1/仅看有货 空/全部
statusOnSale = ""
# 品相成色 1（新品、未使用）/2（几乎未使用）/3（没有明显的划痕或污垢）/4（有一些划痕和污渍）/5（有划痕和污垢）/6（整体状况不佳） 空/全部
conditionIds = ""
# 2/日本内包邮 空/全部
shippingPayer = ""

category = ""
brand_ids = ""


# 骏河屋
# 1/仅看现货
haveStock = ""
# 2/新上架
newPublish = ""

# 1/不限 2/新品 3/二手 4/预约
conditionId = ""
# 1/2/3/4/5/6/7
discountId = ""
# 1029/吧唧
category = ""