# 任你购 配置
# 官网: https://rennigou.jp

# 任你购 网站的搜索设置
[[websites.rennigou.searches]]
# 搜索关键字，必填项
keyword = "家庭教師ヒットマンREBORN"

# 搜索网站，必填项
# 全部-all, 煤炉-mercari, 雅虎日拍-yahooauction，乐天Rakuma-rakuma，亚马逊Amazon-amazon，骏河屋-surugaya
websiteType = "surugaya"

# 通知方式
# from * to *
# 必填项
# 第一项 @Samiya310Bot（1），@Lihahadear_bot（2），企业微信Samiya（3）
# 第二项 根据notify中填的ids定
notify = [1,2]


[websites.rennigou.searches.filter]
# >>>>>>>>>>>>>>煤炉过滤器>>>>>>>>>>>>>>>>>>>>>>>
# 推荐排序-为空，价格降序-price_desc，价格升序-price_asc，上架日期从近到远-new，点赞从多到少-like_desc
sortOrder = ""

# 仅看有货-勾选为1，不勾选为空
statusOnSale = "1"

# 仅看现货-勾选为1，不勾选为空
haveStock = "1"

# 日本国内包邮-勾选为2，不勾选为空
shippingPayer = ""

# 新品、未使用-1，几乎未使用-2，没有明显的划痕或污垢-3，有一些划痕和污渍-4，有划痕和污垢-5，整体状况不佳-6，全部-空
conditionIds = ""
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# >>>>>>>>>>>>>>骏河屋过滤器>>>>>>>>>>>>>>>>>>>
# 默认-为空，价格从低到高-price_asc，价格从高到低-price_desc，新上架商品-new_publish，发售日从进到远-publish_time_asc，发售日从远到近-publish_time_desc
sortOrder = ""

# 仅看现货-勾选为1，不勾选为空
haveStock = "1"

# 新上架-勾选为2，不勾选为空
newPublish = ""

# 折扣 不限为1，后续递增到7，7为>100%
discountId = "1"

# 分类，1029/吧唧
category = ""

# 1/不限 2/新品 3/二手 4/预约
conditionId = "1"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


# >>>>>>>>>>>>>>雅虎日拍过滤器>>>>>>>>>>>>>>>>>>>>>
# TODO
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# >>>>>>>>>>>>>>>Rakuma过滤器>>>>>>>>>>>>>>>>>>>>
# TODO
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# >>>>>>>>>>>>>>>亚马逊过滤器>>>>>>>>>>>>>>>>>>>>>
# TODO
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
