# 用户名称，可选项，默认为 Default User
user = "User Name"

[notify]
# 微信企业号用户ID，与telegram_chat_id至少需要一个
wecom_user_id = ""
# Telegram聊天ID，与wecom_user_id至少需要一个
telegram_chat_id = ""
# 发送类型，可选项，1代表text，2代表img，3代表news，默认为3
tg_send_type = ""
we_send_type = ""

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>指南针<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[websites.lashinbang]
# 是否启用该网站的监控，可选项，默认值为 False
enabled = true
# 监控延迟（秒），可选项，默认值为60
delay = 1200
# 汇率，可选项，默认值为 0.049
exchange_rate = 0.049
# 自定义消息模板，可选项，如果为空将使用默认模板
msg_tpl = """
【$priceStatus】$productName
【链接】$productURL
【价格】$price 円 == $priceCurrency 元
"""
[[websites.lashinbang.searches]]
# 搜索关键字，必填项
keyword = ""
# 通知方式，必填项，1代表tg_1，2代表tg_2，3代表wecom_1，4代表wecom_4
notify = ""
# 最低价格，可选项
price_min = ""
# 最高价格，可选项
price_max = ""

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>煤炉搜索<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[websites.mercari]
# 是否启用该网站的监控，可选项，默认值为 False
enabled = true
# 监控延迟（秒），可选项，默认值为60
delay = 1200
# 汇率，可选项，默认值为 0.049
exchange_rate = 0.049
# 自定义消息模板，可选项，如果为空将使用默认模板
msg_tpl = """
【$priceStatus】$productName
【链接】$productURL
【价格】$price 円 == $priceCurrency 元
"""
[[websites.mercari.searches]]
# 搜索关键字，必填项
keyword = ""
# 通知方式，必填项，1代表tg_1，2代表tg_2，3代表wecom_1，4代表wecom_4
notify = ""
# 排除关键词，可选项
exclude_keyword = ""
# 商品状态，可选项，默认为on_sale
status = ""
# 最低价格，可选项
price_min = ""
# 最高价格，可选项
price_max = ""
# 品类，可选项
category = ""
# 品牌，可选项
brand = ""

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>煤炉卖家<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[websites.mercari_user]
# 是否启用该网站的监控，可选项，默认值为 False
enabled = true
# 监控延迟（秒），可选项，默认值为60
delay = 1200
# 汇率，可选项，默认值为 0.049
exchange_rate = 0.049
# 自定义消息模板，可选项，如果为空将使用默认模板
msg_tpl = """
【$priceStatus】$productName
【链接】$productURL
【价格】$price 円 == $priceCurrency 元
"""
[[websites.mercari_user.searches]]
# 卖家ID，必填项
keyword = ""
# 通知方式，必填项，1代表tg_1，2代表tg_2，3代表wecom_1，4代表wecom_4
notify = ""

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>PayPay<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[websites.paypay]
# 是否启用该网站的监控，可选项，默认值为 False
enabled = true
# 监控延迟（秒），可选项，默认值为60
delay = 1200
# 汇率，可选项，默认值为 0.049
exchange_rate = 0.049
# 自定义消息模板，可选项，如果为空将使用默认模板
msg_tpl = """
【$priceStatus】$productName
【链接】$productURL
【价格】$price 円 == $priceCurrency 元
"""
[[websites.paypay.searches]]
# 搜索关键字，必填项
keyword = ""
# 通知方式，必填项，1代表tg_1，2代表tg_2，3代表wecom_1，4代表wecom_4
notify = ""

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>JumpShop<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[websites.jumpshop]
# 是否启用该网站的监控，可选项，默认值为 False
enabled = true
# 监控延迟（秒），可选项，默认值为60
delay = 1200
# 汇率，可选项，默认值为 0.049
exchange_rate = 0.049
# 自定义消息模板，可选项，如果为空将使用默认模板
msg_tpl = """
【$priceStatus】$productName
【链接】$productURL
【价格】$price 円 == $priceCurrency 元
"""
[[websites.jumpshop.searches]]
# 搜索关键字或者搜索链接，必填项
keyword = ""
# 通知方式，必填项，1代表tg_1，2代表tg_2，3代表wecom_1，4代表wecom_4
notify = ""

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Fril<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[websites.fril]
# 是否启用该网站的监控，可选项，默认值为 False
enabled = true
# 监控延迟（秒），可选项，默认值为60
delay = 1200
# 汇率，可选项，默认值为 0.049
exchange_rate = 0.049
# 自定义消息模板，可选项，如果为空将使用默认模板
msg_tpl = """
【$priceStatus】$productName
【链接】$productURL
【价格】$price 円 == $priceCurrency 元
"""
[[websites.fril.searches]]
# 搜索关键字或者搜索链接，必填项
keyword = ""
# 通知方式，必填项，1代表tg_1，2代表tg_2，3代表wecom_1，4代表wecom_4
notify = ""


# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>骏河屋<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[websites.suruga]
# 是否启用该网站的监控，可选项，默认值为 False
enabled = true
# 监控延迟（秒），可选项，默认值为60
delay = 1200
# 汇率，可选项，默认值为 0.049
exchange_rate = 0.049
# 自定义消息模板，可选项，如果为空将使用默认模板
msg_tpl = """
【$priceStatus】$productName
【链接】$productURL
【价格】$price 円 == $priceCurrency 元
"""
[[websites.suruga.searches]]
# 搜索关键字或者搜索链接，必填项
keyword = ""
# 通知方式，必填项，1代表tg_1，2代表tg_2，3代表wecom_1，4代表wecom_4
notify = ""