name: Build and Publish Docker Image

on:
  release:
    types: [published]
  watch:
    types: [started]  # 当仓库被star时触发
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          samiya777/vintagevigil:${{ github.event.release.tag_name }}
          samiya777/vintagevigil:latest
        platforms: linux/amd64,linux/arm64