name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dockerfile_tag:
        description: 'Dockerfile 标签'
        required: true
        default: 'latest'
      dockerfile_alpine_tag:
        description: 'Dockerfile-Alpine 标签'
        required: true
        default: 'alpine'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image (Latest Tag)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: samiya777/vintagevigil:${{ github.event.inputs.dockerfile_tag || 'latest' }}
        platforms: linux/amd64,linux/arm64

    - name: Build and Push Docker Image (Alpine Tag)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-Alpine
        push: true
        tags: samiya777/vintagevigil:${{ github.event.inputs.dockerfile_alpine_tag || 'alpine' }}
        platforms: linux/amd64,linux/arm64